/* Auto-generated by pwa2nx */
#pragma once

#define APP_TITLE "Spotify"
#define TARGET_URL "https://open.spotify.com"
#define SAFE_NAME "Spotify"
#define GITHUB_REPO "FaserF/pwa2nx"
#define ENABLE_BACKGROUND_PLAYBACK 1
