/* Auto-generated by pwa2nx */
#pragma once

#define APP_TITLE "Universal App"
#define TARGET_URL "universal"
#define SAFE_NAME "Universal_App"
#define GITHUB_REPO "FaserF/pwa2nx"
#define ENABLE_BACKGROUND_PLAYBACK 1
